### PR TITLE
Update microservice with new name field among multiscales.

### PR DESCRIPTION
**Pull request by mtbc**
Following https://forum.image.sc/t/37930 add a `name` field to `multiscales` element in `.zattrs` endpoint.

### CODE REVIEW

**Comment by joshmoore** [comment]
A value is certainly being returned:

```
ome_zarr info http://localhost:8080/idr/zarr/v0.1/1.zarr
root_attrs {'multiscales': [{'name': 'a.fake',
```

but I'm not sure this is the right one. The names are a way to differentiate between the different multi scales, if there are multiple. Perhaps for the case where there is only one either just `default` or the image name with `(default)` appended would be clearer?

**Comment by mtbc** [comment]
Ah, I didn't know what the name was for. Maybe best to omit the image name from the string and simply use the plane size as the name?

**Comment by mtbc** [comment]
Ah, no, sorry, I got the level wrong: the microservice will return only one name so, yes, "default" sounds good, I'll adjust accordingly.

**Comment by joshmoore** [comment]
```
$ ome_zarr info http://localhost:8080/idr/zarr/v0.1/1.zarr
root_attrs {'multiscales': [{'name': 'default',
```
:+1:

**Pull request merged**
