### PR TITLE
Update HTTP microservice to offer Zarr.

### PR DESCRIPTION
**Pull request by mtbc**
# Testing

Use `gradle run --args=etc/omero.properties` as from the README to start the microservice from your OMERO server environment.

Now use the microservice to download an image to the current directory, e.g.,
```
mkdir my-image-1234
cd my-image-1234
/some/path/src/scripts/fetch-ms-zarr.py localhost 8080 1234
```
to download the image.

If the image had subresolutions then take a look at `python -m json.tool .zattrs`

then `cd` into one of the subfolders which are per-resolution. Otherwise, you're effectively already in one.

Take a look at `python -m json.tool .zarray`

Now from somewhere with a `.zarray` we can try firing up napari. From within Python,
```python
import dask
import napari
import zarr
store = zarr.NestedDirectoryStore('')
image = dask.array.from_zarr(store)
with napari.gui_qt():
    napari.view_image(image)
```

## Update

When including the newer commit that defaults download to flattened chunks,
```python
import dask
import napari
image = dask.array.from_zarr('')
with napari.gui_qt():
    napari.view_image(image)
```

# Next Steps

Further work might include:
* Update `swagger.yaml` to match what this provides.
* Add unit testing for the microservice.
* Allow configuration of saved output: e.g., grouping, nested or not, chunk size, etc.
* Provide HTML directory listings for remote-as-filesystem, not just file content.
* Allow multi-*z* chunks when *x* * *y* is small.
* Borrow from https://github.com/ome/omero-downloader to write a TIFF exporter and compare the speed of this microservice with OMERO.downloader's use of Blitz.

### CODE REVIEW

**Comment by joshmoore** [comment]
@mtbc : how hard would it be to revert the nesting in this PR?

**Comment by mtbc** [comment]
Probably a one-character change in,
```python
filename = local_prefix + '/'.join(map(str, chunk))
```
Most of the format changes we might want are probably fairly trivial tweaks.

**Comment by mtbc** [comment]
(Similarly trivial if we want dotted bits served in URLs.)

**Comment by mtbc** [comment]
Happy just to get this in and open the "next steps" as issues.

**Comment by joshmoore** [comment]
Since all the other repositories are moving to non-nested/flattened, if that were possible to have here, then we'd be in sync. Otherwise, agreed.

**Comment by mtbc** [comment]
Does the offered URL need to have dots too? Or does it suffice if the Python downloader writes flat?

**Comment by joshmoore** [comment]
The client will GET and HEAD `group/array/0.0.0.0.0`, so I think the former.

**Comment by mtbc** [comment]
Where is that defined? I'd expect to be offering `groupno/.zarray` and `groupno/0.0.0.0.0` and the like. Do the chunks have to be in some `array` subdirectory?

**Comment by joshmoore** [comment]
from https://github.com/ome/omero-ms-zarr/blob/master/spec.md

```
.                             # Root folder, potentially in S3,
├── 123.zarr                  # with a flat list of images by image ID.
└── 456.zarr                  #
    ├── .zgroup               # Each image is a Zarr group with multscale metadata.
    └── 0                     # Each multiscale level is stored as a separate Zarr array.
        ├── .zarray           #
        ├── 0.0.0.0.0         # Chunks are stored with the flat directory layout.
        └── t.c.z.y.x         # All image arrays are 5-dimensional
                              # with dimension order (t, c, z, y, x).
```

**Comment by mtbc** [comment]
Great, thank you, yes, that's what I was expecting. :+1: Should be sorted now.

**Comment by mtbc** [comment]
Now opened various issues against this repository covering the next steps that aren't strongly already on my list.

**Comment by joshmoore** [comment]
Cheers.

**Pull request merged**
