### PR TITLE
Adjust metadata that microservice includes in .zattrs

### LINKED ISSUE #30: include rendering information in metadata from microservice
Will need to bring the rendering bean up in the application context.

### PR DESCRIPTION
**Pull request by mtbc**
Replaces `scale` with an initial pass at OMERO metadata. Fixes #30 and #31.

### CODE REVIEW

**Comment by joshmoore** [comment]
```
(py36) ~ $ome_zarr info http://localhost:8080/idr/zarr/v0.1/151.zarr
root_attrs {'multiscales': [{'datasets': [{'path': '0'}], 'version': '0.1'}], 'omero': {'channels': [{'color': 'FF0000', 'coefficient': 1.0, 'active': True, 'window': {'min': 3.0, 'max': 4095.0, 'start': 3.0, 'end': 4095.0}, 'family': 'linear', 'inverted': False}, {'color': '00FF00', 'coefficient': 1.0, 'active': True, 'window': {'min': 24.0, 'max': 2380.0, 'start': 24.0, 'end': 2380.0}, 'family': 'linear', 'inverted': False}], 'rdefs': {'defaultT': 0, 'model': 'color', 'defaultZ': 118}, 'name': 'B1_C1.tif', 'id': 151}}
```

Screen Shot 2020-05-12 at 09 34 54


After some editing of the values (note channel names):

```
root_attrs {'multiscales': [{'datasets': [{'path': '0'}], 'version': '0.1'}], 'omero': {'channels': [{'color': 'FFFF00', 'coefficient': 1.0, 'active': True, 'label': 'Dapi', 'window': {'min': 3.0, 'max': 4095.0, 'start': 3.0, 'end': 2190.0}, 'family': 'linear', 'inverted': False}, {'color': '6116B1', 'coefficient': 1.0, 'active': True, 'label': 'LaminB1', 'window': {'min': 24.0, 'max': 2380.0, 'start': 24.0, 'end': 1648.0}, 'family': 'linear', 'inverted': False}], 'rdefs': {'defaultT': 0, 'model': 'color', 'defaultZ': 118}, 'name': 'B1_C1.tif', 'id': 151}}
```

Screen Shot 2020-05-12 at 09 41 43


Only thing I notice is that the order of the channels is reversed, but general :+1:

**Comment by will-moore** [comment]
The channel order is the same whichever way you open in `napari` since it adds channels at the top of the list.

**Comment by joshmoore** [comment]
So are you saying it's independent of the order in the metadata? In that case, do we need to order in the plugin somehow?

**Comment by will-moore** [comment]
Hmmm - OK, I didn't check what was happening before I made that comment.
What I'm seeing with:
```
$ napari 'https://s3.embassy.ebi.ac.uk/idr/zarr/v0.1/6001240.zarr/'
```
is the pixel data in the same order as above, but the metadata in a different order.
This is what you get when you give ```napari``` a 5D numpy array with ```{'channel_axis': 1}```.

Previously, with the ```omero napari``` plugin, I was looping through the channels, calling ```viewer.add_image()``` in for each. And this ends up with the first channel on the bottom of the list.

However, I notice in the screenshot above that channel names (and other metadata?) are in the wrong order compared with the pixel data since Dapi (yellow) is labelling the edged of the cells, when it should be in the centre.

**Comment by joshmoore** [comment]
This may be a case where we need to invert the order in the Python layer. I imagine it would make the most sense to the end user to have the channels in their OMERO order.

**Comment by mtbc** [comment]
Two points of clarification:

1. Do I need to fix something about channel order?
1. Is this testing against a server that does have those channel names set? The original file doesn't seem to.

**Comment by joshmoore** [comment]
My testing was done with manual editing of channel names and rendering info. Happy to find a better test for all of us to work from. I'd say that channel metadata should be ordered as it would be in OME-XML / OMERO. We'll fix everything else to match.

**Comment by mtbc** [comment]
After applying `omero cli render set` with,
```yaml
---
channels:
    1:
        active: true
        color: 0000FF
        end: 1500.0
        label: 'LaminB1'
        max: 4095.0
        min: 3.0
        start: 0.0
    2:
        active: true
        color: FFFF00
        end: 1500.0
        label: 'Dapi'
        max: 2380.0
        min: 24.0
        start: 0.0
greyscale: false
t: 1
version: 2
z: 119
```
this PR is giving me,
```json
{
    "multiscales": [
        {
            "datasets": [
                {
                    "path": "0"
                }
            ],
            "version": "0.1"
        }
    ],
    "omero": {
        "channels": [
            {
                "color": "0000FF",
                "coefficient": 1.0,
                "active": true,
                "label": "LaminB1",
                "window": {
                    "min": 3.0,
                    "max": 4095.0,
                    "start": 0.0,
                    "end": 1500.0
                },
                "family": "linear",
                "inverted": false
            },
            {
                "color": "FFFF00",
                "coefficient": 1.0,
                "active": true,
                "label": "Dapi",
                "window": {
                    "min": 24.0,
                    "max": 2380.0,
                    "start": 0.0,
                    "end": 1500.0
                },
                "family": "linear",
                "inverted": false
            }
        ],
        "rdefs": {
            "defaultT": 0,
            "model": "color",
            "defaultZ": 118
        },
        "name": "B1_C1.tif",
        "id": 5251
    }
}
```
and in the webclient the image looks as in IDR.

**Comment by mtbc** [comment]
The channel ordering does seem to match that of IDR webclient, yay.

**Comment by joshmoore** [comment]
Minor note:
```
...
org.openmicroscopy.ms.zarr.TileSizeAdjustmentTest > testAdjustTileSize(DataShape, int)[7350] PASSED
```
this is a bit verbose. (e.g. hid why these are failing locally:

```
TestTokenCreator. Test session token allowed list and read
TestTokenCreator. Test session token forbidden list and read
```

minio wasn't started.)

**Comment by mtbc** [comment]
Yes, would be nice to have gradle better report parameterized tests, things like OMERO.downloader's `TruncatingOutputStreamTest` have many too.

**Comment by will-moore** [comment]
@mtbc Not sure what you mean by "in the webclient the image looks as in IDR."

Having compared webclient and napari, I see that napari shows channels in the reverse order compared to OMERO.
I think napari adds each channel in turn to the top of the list - you can see in the first screenshot above, ```Image``` layer was added first, then ```Image [1]```.
So, we would have to fix this in napari. Curerntly we're passing a 5D numpy/dask array and using the ```channel-index: 1``` to tell napari to split it into channels.

I guess we could do the slicing of channels ourselves (as we did in `omero napari` plugin), but then the ```ome-zarr-py``` would need to return a list of ```[(data, dict), (data, dict)]``` instead of the single ```[(data, dict)]``` we return now.
Unless we can ask napari to support different channel ordering?

**Comment by mtbc** [comment]
> Not sure what you mean by "in the webclient the image looks as in IDR."

I run the microservice with this PR locally with a local import of the image Josh used. I was checking that in my local webclient it all looks the same as when I look at it in IDR's. Then I figure the rendering settings are matching well.

**Comment by joshmoore** [comment]
My primary concern is that `napari http://omero-ms-zarr` and `napari https://s3...` don't currently produce the same representation, which I assume points to some underlying issue. napari natively showing channels in a different order to OMERO.web seems fine; no need to do anything.

**Comment by joshmoore** [comment]
@mtbc: so we're generally thinking this PR is correct, right? Are you adding unit tests here, or shall we get this in?

**Comment by mtbc** [comment]
Yes, we think correct, fine to merge. Am working on unit tests but don't mind if we hold this PR open or leave them to a followup.

**Comment by will-moore** [comment]
Re: "My primary concern is that napari http://omero-ms-zarr and napari https://s3... don't currently produce the same representation" 
Did that get fixed or are you no-longer concerned about it?

**Comment by joshmoore** [comment]
From https://github.com/ome/omero-ms-zarr/pull/35#issuecomment-627293044 I understood it needed to be fixed on the Python side.

**Comment by will-moore** [comment]
Ah, but then you said "napari natively showing channels in a different order to OMERO.web seems fine; no need to do anything." and I don't know what it looks like now, so I don't know what state we're in. I'll try to test locally...

**Comment by mtbc** [comment]
Further to https://github.com/ome/omero-ms-zarr/pull/35#issuecomment-627263531 I'm also happy to do any further tests or webclient screenshots or whatever could assist.

**Comment by will-moore** [comment]
Testing locally:

```
$ napari 'http://localhost:8080/image/52.zarr/'
```
The channel order *is* opposite in napari compared with OMERO, but the metadata matches the pixel data. 👍

**Comment by will-moore** [comment]
Screenshot 2020-05-13 at 14 11 42

**Pull request merged**
